### ISSUE TITLE
제출 전 확인

### ISSUE THREAD

**Issue by lina0322** [lina0322/42seoul_minishell#19]
- [x] check list
- [x] norm
- [x] leak
- [x] 폴더내 다른 파일들?
- [x] 디스코드, 슬랙에 올라온거 좀 확인해볼까낭
- [x] 메이크파일에 아키텍쳐 설정 지우기?

**Comment by lina0322** [comment]
### check list 
내용 확인 중에 bash랑 다른 동작들이 있어서 적어두었습니당!
괜찮은 건지 확인 부탁드립니댜~

```bash
# bash에서
bash-3.2$ exit 3
exit

# 미니쉘에서
bash> exit 3
3
```

```bash
# bash에서
bash-3.2$ exit a
exit
bash: exit: a: numeric argument required
zshell ▶ echo $? 
255

# 미니쉘에서
bash> exit a
bash: exit: a: numeric argument requiredbash-3.2$ echo $?
255
```

```bash
# bash에서
bash-3.2$           # control + c
bash-3.2$ echo $?
1

# 미니쉘에서
bash>             # control + c
bash> echo $?
0

# 추가 문의!
bash>             # control + d
bash-3.2$ 1       # 미니쉘에서 1로 나오는데, bash에서 입력하면 0이 나와요.
# 근데 bash에서 종료되는게 없어서 그런가?? 하고 잘 모르겠어서 남겨둡니당..!
```
======================여기까지 수정함(다솜)
```bash
# bash에서
bash-3.2$ echo hi>hi
bash-3.2$ ls
Makefile        UML             includes        libft           srcs
README.md       hi              input.txt       minishell
bash-3.2$ cat hi
hi

# 미니쉘에서
bash> echo hi>hi
hi>hi
```

```bash
# bash에서
bash-3.2$ echo hello > tmp1 >tmp2>tmp3 > tmp4 echo ABC
bash-3.2$ ls
tmp1            tmp2              tmp3            tmp4
bash-3.2$ cat tmp1 tmp2 tmp3

bash-3.2$ cat tmp4
hello echo ABC

# 미니쉘에서
bash> echo Hello > tmp1 >tmp2>tmp3 > tmp4 echo ABC
# 터져버리므...ㅠ_ㅠ
=================================================================
==57110==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000002eb0 at pc 0x000102492589 bp 0x000308df6110 sp 0x000308df6108
WRITE of size 8 at 0x603000002eb0 thread T0
    #0 0x102492588 in make_new_cmd execve_util.c:47
    #1 0x1024929ff in renewal_cmd execve_util.c:76
    #2 0x102493390 in check_redirection execve_util.c:106
    #3 0x102490a87 in execute_cmd2 execve.c:47
    #4 0x102491ad6 in execute execve.c:121
    #5 0x10248164d in main main.c:28
    #6 0x7fff203b1620 in start+0x0 (libdyld.dylib:x86_64+0x15620)
```


```bash
# bash에서
bash-3.2$ exit | exit
bash-3.2$                # 종료되지 않음

# 미니쉘에서
bash> exit | exit
bash-3.2$              # 종료됨 
```

**Comment by lina0322** [comment]
지금.. 다..시..작..업....중인것

```bash

# 올바른동작
echo "\\"
\
bash-3.2$ echo "\\""
> 

# 지금 동작
echo "\\"
error : quote error
bash> echo "\\""
\"
```
악!!!!
\\두개를 \하나로 바꾼다음에 "앞에있으면 인식하는거.. 이거 수정해야함ㅁㅁㅁㅁㅁㅁㅁ

**Comment by som-syom** [comment]
- 멤릭
![image](https://user-images.githubusercontent.com/60869490/115142929-3ecf5d00-a07f-11eb-8bc2-e4be75e6157e.png)
